"""`vcell demo` -- the positive control, on synthetic cells, in a few minutes.

Runs the registered protocol against `vcell.synthetic`, where the structures
were generated by the very rules the annotation implies. Two things must happen
or the pipeline is broken rather than the biology being hard:

* the geometric rule from annotation must score near the ceiling, because it is
  the generating process;
* the trained model must beat the pooled atlas, including on the leave-one-out
  fold, because the information it needs is genuinely present in the input.
"""

from __future__ import annotations

import numpy as np

from vcell.dataset import split_by_fov
from vcell.report import gene_table, headline_table
from vcell.synthetic import SYNTHETIC_GENES, synth_frames
from vcell.train import evaluate_fold, summarise, train_model


def run_demo(epochs: int = 12, seed: int = 20260914, n_per_gene: int = 18) -> int:
    print(f"building {n_per_gene * len(SYNTHETIC_GENES)} synthetic cells "
          f"({', '.join(SYNTHETIC_GENES)}) ...", flush=True)
    frames = synth_frames(n_per_gene=n_per_gene, seed=seed)
    records: list[dict] = []

    train_idx, test_idx = split_by_fov(frames, test_fraction=0.25, seed=seed)
    model = train_model(frames, train_idx, epochs, 4, seed, log_prefix="[seen] ")
    ablated = train_model(frames, train_idx, epochs, 4, seed, ablate_knowledge=True,
                          log_prefix="[seen/ablated] ")
    records += evaluate_fold("seen", frames, train_idx, test_idx, model, ablated,
                             set(SYNTHETIC_GENES))

    held = "LMNB1"
    print(f"\n[loso_{held}] holding out {held} entirely", flush=True)
    train_idx = np.flatnonzero(frames["gene"] != held)
    test_idx = np.flatnonzero(frames["gene"] == held)
    loso = train_model(frames, train_idx, epochs, 4, seed, log_prefix=f"[loso_{held}] ")
    records += evaluate_fold(f"loso_{held}", frames, train_idx, test_idx, loso, None,
                             set(SYNTHETIC_GENES) - {held})

    summary = summarise(records, seed=seed)
    folds = sorted({r["fold"] for r in summary})
    print("\n" + headline_table(summary, folds))
    for fold in folds:
        for gene in sorted({r["gene"] for r in summary if r["fold"] == fold}):
            print(f"\n### {fold} / {gene}\n")
            print(gene_table(summary, fold, gene))

    checks = _positive_control(summary)
    print("\npositive control:")
    for name, passed, detail in checks:
        print(f"  [{'pass' if passed else 'FAIL'}] {name}: {detail}")
    return 0 if all(p for _, p, _ in checks) else 1


def _positive_control(summary: list[dict]) -> list[tuple[str, bool, str]]:
    """Checks the pipeline must pass on a world whose answers are known.

    Note what is *not* checked. The synthetic TOMM20 blobs are seeded at random
    positions in the cytoplasm, so nothing in the reference channels predicts
    them -- that line is the built-in negative control, and a predictor that
    beat chance on it would mean the metrics are gameable rather than that the
    model is clever. Its numbers are printed for inspection, not asserted.
    """

    def value(fold: str, gene: str, predictor: str, metric: str = "dice") -> float:
        for row in summary:
            if (row["fold"], row["gene"], row["predictor"]) == (fold, gene, predictor):
                return float(row[metric])
        return float("nan")

    out = []
    rule = value("seen", "LMNB1", "rule_annotation")
    out.append((
        "generating rule recovers its own structure",
        np.isfinite(rule) and rule > 0.5,
        f"annotation rule Dice on LMNB1 = {rule:.3f} (expected > 0.5)",
    ))
    for fold, gene in (("seen", "LMNB1"), ("seen", "FBL"), ("loso_LMNB1", "LMNB1")):
        model = value(fold, gene, "model")
        atlas = value(fold, gene, "atlas_pooled")
        out.append((
            f"model beats pooled atlas on {fold}/{gene}",
            np.isfinite(model) and np.isfinite(atlas) and model > atlas,
            f"model Dice {model:.3f} vs pooled atlas {atlas:.3f}",
        ))
    negative = value("seen", "TOMM20", "model")
    print(f"  [info] negative control, synthetic TOMM20 (random blobs): "
          f"model Dice {negative:.3f} -- expected near chance")
    return out
