"""A synthetic cell world with known ground truth. No network, no images.

This is a **positive control for the whole pipeline**. The synthetic structures
are generated by exactly the geometric rules that `vcell.baselines` implements
and that `vcell.knowledge` annotates: the LMNB1 cell line gets a shell around
the nucleus, TOMM20 gets cytoplasmic blobs, FBL gets a nucleolar blob inside the
nucleus. So the annotation-to-location map is *true by construction* here.

That makes the demo diagnostic rather than decorative. If the protocol cannot
recover a world where the answer is a deterministic function of the annotation
and the masks, then a null result on real cells says nothing about cells -- it
says the frame, the loss, the metrics or the split are broken. Running this
first is how you tell those two situations apart.

Volumes are emitted in the raw Allen layout -- (Z, C, Y, X) uint16 alongside a
(Z, C, Y, X) uint8 segmentation -- so they travel through `build_frame` on the
same path a real crop does, and the frame code is exercised too.
"""

from __future__ import annotations

import numpy as np

from vcell.frame import CANONICAL_GRID, build_frame

# Real gene names, because the point is to exercise the real knowledge vectors.
SYNTHETIC_GENES = ("LMNB1", "TOMM20", "FBL")
SYNTHETIC_SCALE_MICRON = 0.15


def _ellipsoid(shape: tuple[int, int, int], centre, radii, rng=None) -> np.ndarray:
    grids = np.indices(shape).astype(np.float32)
    value = sum(
        ((g - c) / max(r, 1e-3)) ** 2 for g, c, r in zip(grids, centre, radii, strict=True)
    )
    if rng is not None:
        # A wobbly surface, so the frame is not solving a perfectly regular problem.
        value = value * (1.0 + 0.12 * rng.standard_normal(shape).astype(np.float32))
    return value <= 1.0


def synth_cell(
    gene: str,
    rng: np.random.Generator,
    shape: tuple[int, int, int] = (48, 120, 136),
) -> tuple[np.ndarray, np.ndarray]:
    """One synthetic (raw, seg) pair in the Allen crop layout."""
    z, y, x = shape
    centre = (z / 2, y / 2, x / 2)
    # Random cell shape and orientation-ish elongation, so the frame has work to do.
    cell_radii = (
        z * rng.uniform(0.30, 0.40),
        y * rng.uniform(0.30, 0.42),
        x * rng.uniform(0.30, 0.42),
    )
    cell = _ellipsoid(shape, centre, cell_radii, rng)
    offset = (
        rng.uniform(-2, 2),
        y * rng.uniform(-0.06, 0.06),
        x * rng.uniform(-0.06, 0.06),
    )
    nuc_centre = tuple(c + o for c, o in zip(centre, offset, strict=True))
    nuc = _ellipsoid(shape, nuc_centre, tuple(r * 0.45 for r in cell_radii), rng) & cell
    cyto = cell & ~nuc

    from scipy import ndimage

    if gene == "LMNB1":  # a shell straddling the nuclear surface
        d_out = ndimage.distance_transform_edt(~nuc)
        d_in = ndimage.distance_transform_edt(nuc)
        structure = (np.where(nuc, d_in, d_out) <= 2.0) & cell
    elif gene == "FBL":  # one blob inside the nucleus
        blob_centre = tuple(
            c + rng.uniform(-3, 3) for c in ndimage.center_of_mass(nuc)
        )
        structure = _ellipsoid(shape, blob_centre, (5, 11, 11), rng) & nuc
    elif gene == "TOMM20":  # blobs scattered through the cytoplasm
        seeds = np.zeros(shape, dtype=bool)
        rows = np.array(np.nonzero(cyto))
        if rows.shape[1] > 0:
            pick = rng.choice(rows.shape[1], size=min(60, rows.shape[1]), replace=False)
            seeds[tuple(rows[:, pick])] = True
        structure = ndimage.binary_dilation(seeds, iterations=4) & cyto
    else:  # pragma: no cover - guarded by SYNTHETIC_GENES
        raise ValueError(f"no synthetic recipe for {gene!r}")

    if not structure.any():  # pragma: no cover - degenerate draw
        structure = cyto

    def channel(mask: np.ndarray, level: float) -> np.ndarray:
        signal = ndimage.gaussian_filter(mask.astype(np.float32), 1.2) * level
        noise = rng.normal(0.0, 0.02 * level, shape).astype(np.float32)
        return np.clip((signal + noise + 0.05 * level) * cell, 0, None)

    raw = np.stack(
        [channel(nuc, 3000.0), channel(cell & ~nuc, 2200.0), channel(structure, 2600.0)],
        axis=1,
    ).astype(np.uint16)
    seg = np.stack(
        [
            nuc.astype(np.uint8) * 255,
            cell.astype(np.uint8) * 255,
            cell.astype(np.uint8) * 255,  # roof channel, unused here
            structure.astype(np.uint8) * 255,
            structure.astype(np.uint8) * 255,
        ],
        axis=1,
    )
    return raw, seg


def synth_frames(
    n_per_gene: int = 18,
    genes: tuple[str, ...] = SYNTHETIC_GENES,
    grid: tuple[int, int, int] = CANONICAL_GRID,
    seed: int = 0,
) -> dict[str, np.ndarray]:
    """A frames dict in the same layout `vcell.dataset.load_frames` returns."""
    rng = np.random.default_rng(seed)
    built = []
    for gene in genes:
        for i in range(n_per_gene):
            raw, seg = synth_cell(gene, rng)
            built.append(
                build_frame(
                    raw,
                    seg,
                    scale_micron=SYNTHETIC_SCALE_MICRON,
                    grid=grid,
                    cell_id=f"{gene}-{i}",
                    fov_id=f"{gene}-fov{i}",
                    gene=gene,
                    cell_stage="M0",
                )
            )
    return {
        "reference": np.stack([f.reference for f in built]).astype(np.float16),
        "target": np.stack([f.target for f in built]).astype(np.float16),
        "struct_mask": np.stack([f.struct_mask for f in built]),
        "nuc_mask": np.stack([f.nuc_mask for f in built]),
        "cell_mask": np.stack([f.cell_mask for f in built]),
        "voxel_micron": np.stack([f.voxel_micron for f in built]),
        "cell_id": np.array([f.cell_id for f in built]),
        "fov_id": np.array([f.fov_id for f in built]),
        "gene": np.array([f.gene for f in built]),
        "cell_stage": np.array([f.cell_stage for f in built]),
    }
