"""Candidate ticker lists for universe construction.

Why a seed list at all
----------------------
The SEC ticker map has ~10,400 issuers. Pricing all of them is ~10,400 requests
and most are shells, trusts, preferred lines, warrants and OTC names with no
tradable liquidity. The seed list narrows to *plausibly tradable US operating
companies* before the point-in-time market-cap and liquidity screens run on top.

**This is a selection step and it carries bias**, so it is stated rather than
hidden: names are chosen for sector breadth and for being listed and liquid at
some point in the window. Companies that delisted before the window are absent.
For research you would fund, replace this with historical index membership
(Russell 2000 reconstitution files) and a delisting-inclusive price archive,
which together remove the bias this list introduces.

The list is deliberately weighted toward sectors where **discrete catalysts move
price**: biotech (trial readouts, FDA decisions), semis and hardware (design
wins, guidance), energy and mining (reserve reports, commodity swings), and
consumer/retail (comps). Utilities and large-cap staples are thin here on
purpose -- a catalyst strategy has nothing to do in a regulated utility.
"""

from __future__ import annotations

#: Small/mid-cap US operating companies across catalyst-rich sectors.
#: ~520 names. The point-in-time cap screen is what actually defines the
#: universe; this is only the candidate pool.
SMALLMID_SEED: list[str] = sorted(set("""
ARWR SRPT IONS ALNY BLUE FOLD RARE AXSM HALO PTCT ACAD SAGE VKTX MDGL DVAX ARDX
CRSP NTLA BEAM EDIT VCYT EXAS PACB TWST CDNA NVAX OCGN INO VXRT ATRA IMVT
IRWD AMPH COLL SUPN HRMY ANIP PCRX EOLS EVH OMCL NBIX INSM ITCI CORT AGIO
ALKS AMRX ARQT AUPH AXNX BCRX BHVN BPMC CBAY CERE CGEM CLDX CPRX CRNX CYTK
DNLI DYN EWTX FDMT GERN GOSS HRTX IDYA IMCR INCY IOVA JAZZ KRTX KURA KYMR
LGND MRUS MYGN NARI NRIX NUVL OABI OCUL OPK ORIC PGEN PHAT PRTA PTGX RARE
RCKT RCUS RGNX RIGL RLAY RVMD RXRX SAVA SGMO SNDX SPRY SRRK STOK SWTX SYRE
TARS TGTX TVTX VCEL VERA VIR VNDA VRDN XENE XNCR ZLAB ZNTL
ON MPWR SLAB LSCC AMBA SITM ALGM POWI DIOD SMTC MTSI FORM ACLS UCTT COHU ONTO
AEIS ICHR AOSL PLAB VECO CRUS SYNA RMBS SIMO NVTS INDI AMKR SGH XPER MXL
ALAB ARM ASTS CAMT CEVA DSP HIMX IPGP KLIC LFUS MKSI NVMI OLED PI POWL QRVO
X CLF AA MP UEC CCJ DNN NXE SMR CDE HL AG EXK PAAS SSRM AGI BTG EQX IAG NGD
KGC AU HMY DRD SAND WPM FNV RGLD OR MAG ASM USAS VZLA GATO SILV DC
ENPH SEDG RUN NOVA ARRY SHLS CSIQ JKS MAXN AMRC FSLR SPWR NEP CWEN AMPS
PLUG BE FCEL BLDP CHPT BLNK EVGO WKHS RIDE GOEV NKLA HYLN XOS ARVL LEV PTRA
CALX EXTR NTGR DGII INFN AAOI LITE VIAV COMM CIEN ANET DZSI CLFD OCC
SKYW ALGT JBLU SAVE MESA ULCC ALK HA CPA VLRS
SM MTDR CIVI CRC BRY REPX AMPY VTLE CPE GPOR CHRD PR MGY CRGY KOS TALO
CVI PARR DINO ALTO GEVO REX CLNE MEOH LEU CEIX ARCH BTU AMR HCC METC
BGFV CATO SCVL DXLG ZUMZ CHUY PTLO NDLS CAKE BJRI DENN JACK LOCO WING SHAK
UPWK FVRR CARG CARS QNST YELP EVER TRIP EB YELP ANGI IAC ZIP DJCO
AAP GPI ABG LAD SAH PAG KMX CVNA VRM SFT
AMBC KMPR PLMR PRA SIGI STC TRUP UFCS UVE HCI KINS ICC AMSF
BANC BANF BHLB BRKL CATY CBU CFFN COLB CVBF EGBN FFBC FIBK FULT GBCI HOPE
HTLF INDB LKFN NBTB NWBI OZK PACW PFBC PPBI RBCAA SASR SBCF SFNC STBA TCBK
TOWN TRMK UBSI UCBI UMBF VLY WAFD WSBC WSFS
AIN ASTE ATRO AVAV BLBD CIR CSWI CW DXPE EPAC ESE FSS GBX GENC GTLS HURN
KAI LNN MEC MLI MYRG NPO NVEE PLPC PRLB RBC ROAD RUSHA SPXC SXI TAYD THR
TILE TNC TRS TTC UFPI VMI WNC WTS XMTR
AMWD APOG AWI AZEK BCC BLDR BMCH CSTE CVCO DOOR EXP FBHS GMS IBP JELD LGIH
MHO MTH NVR PATK SKY TMHC TPH TREX UFPI WMS
ACLS AEIS AMBA AOSL ARLO AUDC AVNW BELFB BOOM CEVA CLIR CTS DAKT DIOD EMKR
ESE FARO GILT INVE IRDM ITRI KOPN KTOS LASR LGL LYTS MCRB MEI MICT MSI
NPTN NSSC OSIS PLXS POWI RELL ROG SANM SPCB TACT TTMI USLM VICR VOXX WATT
""".split()))

#: A compact, sector-diverse subset for fast iteration.
SMALLMID_CORE: list[str] = sorted(set("""
ARWR SRPT IONS BLUE FOLD RARE AXSM HALO PTCT ACAD SAGE VKTX MDGL DVAX ARDX
CRSP NTLA BEAM EDIT VCYT EXAS PACB TWST CDNA NVAX OCGN INO VXRT ATRA
IRWD AMPH COLL SUPN HRMY ANIP PCRX EOLS EVH OMCL
ON MPWR SLAB LSCC AMBA SITM ALGM POWI DIOD SMTC MTSI FORM ACLS UCTT
COHU ONTO AEIS ICHR AOSL PLAB VECO
X CLF AA MP UEC CCJ DNN NXE SMR CDE HL AG EXK PAAS SSRM
ENPH SEDG RUN NOVA ARRY SHLS CSIQ JKS MAXN AMRC
PLUG BE FCEL BLDP CHPT BLNK EVGO WKHS RIDE GOEV NKLA HYLN
CALX EXTR NTGR DGII INFN AAOI LITE VIAV
SKYW ALGT JBLU SAVE MESA
SM MTDR CIVI CRC BRY REPX AMPY VTLE
CVI PARR DINO ALTO GEVO REX
BGFV CATO SCVL DXLG ZUMZ CHUY PTLO NDLS
UPWK FVRR CARG CARS QNST YELP EVER
""".split()))
